IDB queue
kheina-com/Blue-Blocker pull request #177
Opened 2023-07-03 05:20 UTC by DanielleMiu

2023-09-24 20:27 UTC, cooljeanius commented on src/pages/queue/index.html
> +			<p id="db-limit-reached" class="subtitle">holy shit your queue is huge, results have been limited to the first 10,000</p>
is it expected that this could actually be reached?

2023-09-24 20:29 UTC, cooljeanius submitted a review, later dismissed

2024-03-03 22:29 UTC, rougetimelord commented
Went through and resolved merge conflicts as best as I can! Hopefully I didn't mess anything up

2024-03-03 22:54 UTC, cooljeanius submitted a review, later dismissed

2024-03-03 22:54 UTC, cooljeanius commented on src/pages/queue/index.html
> +			<p id="db-limit-reached" class="subtitle">holy shit your queue is huge, results have been limited to the first 10,000</p>
@rougetimelord WDYT?

2024-04-15 06:31 UTC, rougetimelord approved these changes

2024-04-15 06:32 UTC, rougetimelord commented
I'll test then merge tomorrow!

2024-04-15 17:38 UTC, cooljeanius commented on src/pages/queue/index.html
> +			<p id="db-limit-reached" class="subtitle">holy shit your queue is huge, results have been limited to the first 10,000</p>
ok, going to resolve this, then

2024-04-15 18:02 UTC, rougetimelord commented
Ok that's all of the problems my JS linter found

2024-04-15 18:08 UTC, cooljeanius submitted a review, later dismissed

2024-04-15 18:13 UTC, rougetimelord approved these changes
Fixed it, all good. On to testing then merging #120 into this PR

2024-04-15 18:13 UTC, rougetimelord commented on src/background/index.ts
> +import { api, logstr, AddToHistoryAction, ErrorStatus, IsVerifiedAction, ReasonExternal, RemoveFromHistoryAction, SoupcanExtensionId, SuccessStatus, DefaultOptions, AddToQueueAction, PopFromQueueActi
Disregard, figured it out :)

2024-04-15 23:29 UTC, rougetimelord commented
Alright, no more new code. Haven't run into any issues in my testing, but would still like a once over before merging

2024-04-16 00:48 UTC, cooljeanius requested changes

2024-04-16 00:48 UTC, cooljeanius commented on src/constants.ts
> +export const IntegrationStateSendOnly = 3;
fix up whitespace here please (newline at EOF)

2024-04-16 01:47 UTC, rougetimelord commented on src/constants.ts
> +export const IntegrationStateSendOnly = 3;
Done!

2024-04-16 02:53 UTC, cooljeanius approved these changes

2024-04-16 20:54 UTC, merged